//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace up2711.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries_Andriyanova
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Capital { get; set; }
        public string Continent { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<int> Square { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Management_Andriyanova Management_Andriyanova { get; set; }
    }
}
